name: Deploy Walrus Site

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Walrus
        uses: MystenLabs/walrus-sites/.github/actions/deploy@main
        with:
          SUI_ADDRESS: ${{ vars.SUI_ADDRESS }}
          SUI_KEYSTORE: ${{ secrets.SUI_KEYSTORE }}
          DIST: site
          SUI_NETWORK: mainnet
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}